taco:
  orders:
    pageSize: 10

logging:
  level:
    study.davincijcloud: DEBUG

---
spring:
  datasource:
    url: jdbc:mysql://localhost/tacocloud
    username: tacouser
    password: tacopassword
  config:
    activate:
      on-profile: prod

logging:
  level:
    study.davincijcloud: WARN